#!/bin/sh

# This script uses a 'database', which is a simple directory containing the
# todo items. A todo item is a subdirectory of the database that contains files
# associated with it, like its title and whether or it is done.
#
# In order to easily reference items when issuing commands like `delete' or
# `toggle', each item is given an ID. IDs are tracked using the `id' file in
# database directory. This ID is also the name of the todo item's directory.

# By order of priority, the path to the database is set to $TODO_DB, then to a
# subdir of $XDG_DATA_HOME, or if neither of these vars are set, $HOME/.todo
if [ $TODO_DB ]; then
  db="$TODO_DB"
elif [ $XDG_DATA_HOME ]; then
  db="$XDG_DATA_HOME/todo"
else
  db="$HOME/.todo"
fi

# As explained in the top-level comment, this file tracks IDs for the items.
idfile="$db/id"

# If they do not exist, create the database directory and the ID file.
mkdir -p "$db"
if [ ! -f "$idfile" ]; then
  echo 0 > "$idfile"
fi

get_new_id() {
  current_id=$(cat $idfile)
  new_id=$(expr $current_id + 1)
  echo $new_id > "$idfile"
  return $new_id
}

# Main function for listing todo items. Takes no arguments for now.
go_ls() {
  for item in $(ls "$db"); do
    item_path="$db/$item"
    if [ "$item_path" = "$idfile" ]; then
      continue
    fi
    if [ -f "$item_path/done" ]; then
      item_state="X"
    else
      item_state="."
    fi
    item_title=$(cat "$item_path/title")
    printf '%s%s\t%s\n' $item "$item_state" "$item_title"
  done
}

# Main function for adding a new todo item. Takes a single argument, the title
# of the item to create. It does not matter if another item with the same name
# already exists in the database.
go_add() {
  item_name="$1"
  if [ -z "$item_name" ]; then
    echo "usage: $0 add name"
    exit 1
  fi
  get_new_id
  item_id=$?
  item_path="$db/$item_id"
  mkdir "$item_path"
  echo "$item_name" > "$item_path/title"
  echo $item_id
}

# Toggle the state (`to do' or `done') of an item by removing or creating a
# flag file named `done' in the item's directory. Takes a single argument, the
# ID of the item to toggle.
go_toggle() {
  item_id=$1
  if [ -z $item_id ]; then
    echo "usage: $0 toggle id"
    exit 1
  fi
  item_path="$db/$item_id"
  if [ ! -d "$item_path" ]; then
    echo "item does not exist!"
    exit 2
  fi
  if [ ! -f "$item_path/done" ]; then
    touch "$item_path/done"
  else
    rm "$item_path/done"
  fi
}

# Deletes all completed items. Takes no arguments.
go_clean() {
  for item in $(ls "$db"); do
    item_path="$db/$item"
    if [ "$item_path" = "$idfile" ]; then
      continue
    fi
    if [ -f "$item_path/done" ]; then
      rm -fr "$item_path"
    fi
  done
}

# Deletes, after user confirmation, a given todo item. Takes a single argument,
# the ID of the item to remove.
go_delete() {
  item_id=$1
  if [ -z $item_id ]; then
    echo "usage: $0 delete id"
    exit 1
  fi
  item_path="$db/$item_id"
  if [ ! -d "$item_path" ]; then
    echo "item does not exist!"
    exit 2
  fi
  item_title=$(cat "$item_path/title")
  echo "$item_title"
  while true; do
    read -p 'remove? [y/N] ' confirm
    case "$confirm" in
      [Yy])
        rm -fr "$item_path"
        break;;
      [Nn]|'') exit 0;;
    esac
  done
}

# Just absolutely nuke the database, after a user confirmation.
go_nuke() {
  while true; do
    read -p "nuke EVERYTHING by removing $db? [y/N] " confirm
    case "$confirm" in
      [Yy])
        rm -fr "$db" # ciao
        break;;
      [Nn]|'') exit 0;;
    esac
  done
}

# The first command-line argument should be one of: ls, add, toggle, delete,
# nuke, clean.
#
# Only the first letter of each argument is checked. If no such arguments are
# given, assume 'ls' to list all tasks.
case $1 in
  l*)
    shift
    go_ls $@;;
  a*)
    shift
    go_add "$@";;
  t*)
    shift
    go_toggle $@;;
  d*)
    shift
    go_delete $@;;
  c*)
    shift
    go_clean $@;;
  n*)
    shift
    go_nuke $@;;
  -h|--help)
    echo "usage: $0 [ls|add|toggle|delete|clean|nuke]"
    echo "       $0 -h|--help"
    echo "       $0 -r|--reset-id"
    exit 1;;
  -r|--reset-id)
    echo 0 > "$idfile"
    ;;
  *)
    go_ls $@;;
esac
